Repository FrancoNB/GymCore, pull requests merged in 2022-06, with the labels that each got.

#105 PaymentsModelTest_v1.0
  BusinessLayerTest/BusinessLayerTest.csproj
  BusinessLayerTest/ModelsTests/PaymentsModelTest.cs
Labels: enhancement

#106 IntegrationTests_v1.1
  BusinessLayer/Models/PaymentsModel.cs
  IntegrationTest/IntegrationTest.csproj
  IntegrationTest/IntegrationTests/AssistsIntegrationTest.cs
  IntegrationTest/IntegrationTests/PaymentsIntegrationTest.cs
Labels: bug, enhancement

#111 BugFix_v1.1
  BusinessLayer/BusinessLayer.csproj
  BusinessLayer/Cache/AssistsCache.cs
  BusinessLayer/Cache/ClientsCache.cs
  BusinessLayer/Cache/CurrentAccountsCache.cs
  BusinessLayer/Cache/ExercisesCache.cs
  BusinessLayer/Cache/PackagesCache.cs
  BusinessLayer/Cache/PaymentsCache.cs
  BusinessLayer/Cache/SubscriptionsCache.cs
  BusinessLayer/Cache/UsersCache.cs
  BusinessLayer/Models/AssistsModel.cs
  BusinessLayer/Models/ClientsModel.cs
  BusinessLayer/Models/CurrentAccountsModel.cs
  BusinessLayer/Models/ExercisesModel.cs
  BusinessLayer/Models/PackagesModel.cs
  BusinessLayer/Models/PaymentsModel.cs
  BusinessLayer/Models/RoutinesModel.cs
  BusinessLayer/Models/SubscriptionsModel.cs
  BusinessLayer/Models/UsersModel.cs
  BusinessLayer/Models/WorkPlansModel.cs
  BusinessLayer/Services/Assists/AssistsDeleteService.cs
  BusinessLayer/Services/Service.cs
  BusinessLayer/Support/Subscribeable.cs
  PresentationLayer/Forms/Lists/frmClientsList.cs
  PresentationLayer/Forms/Management/frmManagementAssists.cs
  PresentationLayer/Forms/Support/frmMainMenu.cs
Labels: bug

#112 README_v1.1
  README.md
Labels: documentation

#113 README_v1.2
  README.md
Labels: documentation

#114 Installer_v1.0
  BusinessLayer/Models/UsersModel.cs
  DataAccessLayer/Support/RepositoryConnection.cs
  DataAccessLayerTest/app.config
  IntegrationTest/IntegrationTest.csproj
  IntegrationTest/app.config
  PresentationLayer/App.config
  PresentationLayer/PresentationLayer.csproj
  PresentationLayer/Properties/AssemblyInfo.cs
  README.md
Labels: documentation, enhancement

#115 LICENSE
  LICENSE.md
  README.md
Labels: documentation

#117 IC_v1.0
  .github/workflows/integrate.yaml
Labels: bug
